### ISSUE TITLE
Make so mcs can inject the searched dependecny into the pom.

### ISSUE THREAD

**Issue by Alathreon** [mthmulders/mcs#414]
From what I understand, you search with this tool, get the dependency coordinates, copy it, and paste it into the pom.
It would be better if this tool cool ad the dependency directly into the pom.

**Comment by mthmulders** [comment]
Hi @Alathreon, thank you for taking the time to submit this idea. Your understanding of what MCS does is correct. The name gives it away already: it's a tool for _searching_ Maven Central.

Having to integrate with all the build tools and their respective files to update those build files is outside the scope of MCS. There are too many factors to take into account for manipulating such files. Because of that, I will close this issue.

Again, thank you for formulating the idea, and I hope MCS will continue to be a useful tool to you.
